version: '3.8'

services:
  nextjs-app:
    container_name: aither-way
    build:
      context: .
      dockerfile: Dockerfile
    image: aither-way-img
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - .next:/app/.next
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  .next-data: